name = "CausalKernels"
uuid = "8985b3c1-5d09-4d35-a8bc-b2eeed20dbd7"
license = "BSD-2-Clause"
authors = ["kevindirect <git@kevindirect.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticKernels = "4c63dfa8-a427-4548-bd2f-4c19e87a7dc7"

[compat]
julia = "1.8.0"
